import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:file_picker/file_picker.dart';

import '../../../core/l10n/app_localizations.dart';
import '../../../domain/models/staff_quiz_question_model.dart';
import '../../../domain/models/staff_quiz_summary_model.dart';
import '../../../domain/models/staff_reaction_quiz_overview_model.dart';
import '../../../shared/styles/app_colors.dart';
import '../../shared/widgets/portal/portal_widgets.dart';
import '../providers/staff_provider.dart';

class StaffQuizTab extends StatefulWidget {
  const StaffQuizTab({super.key});

  @override
  State<StaffQuizTab> createState() => _StaffQuizTabState();
}

class _StaffQuizTabState extends State<StaffQuizTab> {
  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance.addPostFrameCallback((_) {
      context.read<StaffProvider>().loadReactionQuizOverviews();
    });
  }


  StaffReactionQuizOverviewModel? _selectedReaction;
  StaffQuizSummaryModel? _selectedQuiz;

  Future<void> _refresh() async {
    final provider = context.read<StaffProvider>();

    if (_selectedQuiz != null) {
      await provider.loadQuizDetail(_selectedQuiz!.quizCode);
    } else if (_selectedReaction != null) {
      await Future.wait([
        provider.loadQuizzesByReaction(
          _selectedReaction!.reactionCode,
        ),
        provider.loadReactionQuizPrompt(
          _selectedReaction!.reactionCode,
        ),
      ]);
    } else {
      await provider.loadReactionQuizOverviews();
    }
  }

  Future<void> _pickAndImportCsv(String reactionCode) async {
    final staffProvider = context.read<StaffProvider>();
    final result = await FilePicker.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['csv'],
      withData: true,
    );

    if (result == null || result.files.isEmpty) return;

    final file = result.files.single;
    final bytes = file.bytes;

    if (bytes == null) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Không đọc được file CSV.'),
        ),
      );
      return;
    }

    try {
      await staffProvider.importQuizCsv(
        reactionCode: reactionCode,
        fileName: file.name,
        bytes: bytes,
        fileSize: file.size,
      );

      if (!mounted) return;

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Đã import CSV quiz thành công.'),
        ),
      );

      await _refresh();
    } catch (e) {
      if (!mounted) return;

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Import CSV thất bại: $e'),
          backgroundColor: AppColors.error,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    final staff = context.watch<StaffProvider>();

    final reactions = staff.reactionQuizOverviews;
    final selectedReaction = _selectedReaction;
    final selectedQuizzes = staff.selectedReactionQuizzes;
    final selectedQuiz = _selectedQuiz;
    final selectedQuizDetail = staff.selectedQuizDetail;

    return RefreshIndicator(
      onRefresh: _refresh,
      child: ListView(
        padding: const EdgeInsets.fromLTRB(20, 4, 20, 24),
        children: [
          PortalPrimaryButton(
            label: l10n.isVi
                ? 'Quản lý quiz theo phản ứng'
                : 'Manage quizzes by reaction',
            icon: Icons.quiz_outlined,
            loading:
            staff.loadingReactionQuizOverviews ||
                staff.importingQuizCsv,
            onPressed: _refresh,
          ),
          const SizedBox(height: 8),
          Text(
            l10n.isVi
                ? 'Chọn một phản ứng để xem prompt, import CSV, kiểm tra câu hỏi và publish quiz.'
                : 'Select a reaction to view its prompt, import CSV, review questions, and publish the quiz.',
            style: TextStyle(
              fontSize: 11,
              color: AppColors.textSecondary,
              fontFamily: 'Inter',
            ),
          ),
          const SizedBox(height: 8),
          Text(
            l10n.isVi
                ? 'CSV do AI tạo theo prompt chuẩn — staff kiểm tra trước khi publish.'
                : 'CSV generated by AI using the standard prompt — staff reviews before publishing.',
            style: TextStyle(
              fontSize: 12,
              color: AppColors.subtitleAccent,
              fontFamily: 'Inter',
            ),
          ),
          const SizedBox(height: 20),
          PortalSectionHeader(
            title: l10n.isVi
                ? 'Danh sách phản ứng'
                : 'Reaction list',
            actionLabel: '${reactions.length}',
          ),

          if (selectedReaction == null) ...[
            if (staff.loadingReactionQuizOverviews &&
                reactions.isEmpty)
              const Padding(
                padding: EdgeInsets.only(top: 24),
                child: Center(
                  child: CircularProgressIndicator(),
                ),
              )
            else if (staff.reactionQuizOverviewError != null)
              _ErrorCard(
                message: staff.reactionQuizOverviewError!,
                onRetry: _refresh,
              )
            else if (reactions.isEmpty)
                _EmptyCard(
                  message: l10n.isVi
                      ? 'Chưa có phản ứng nào.'
                      : 'No reactions found.',
                )
              else
                ...reactions.map(
                      (reaction) => _ReactionQuizOverviewCard(
                    reaction: reaction,
                    onViewPrompt: () async {
                      setState(() {
                        _selectedReaction = reaction;
                        _selectedQuiz = null;
                      });

                      final provider =
                      context.read<StaffProvider>();

                      await Future.wait([
                        provider.loadQuizzesByReaction(
                          reaction.reactionCode,
                        ),
                        provider.loadReactionQuizPrompt(
                          reaction.reactionCode,
                        ),
                      ]);
                    },
                    onViewQuizzes: () async {
                      setState(() {
                        _selectedReaction = reaction;
                        _selectedQuiz = null;
                      });

                      final provider =
                      context.read<StaffProvider>();

                      await provider.loadQuizzesByReaction(
                        reaction.reactionCode,
                      );
                    },
                  ),
                ),
          ] else if (selectedQuiz == null) ...[
            _SelectedReactionHeader(
              reaction: selectedReaction,
              onBack: () {
                context
                    .read<StaffProvider>()
                    .clearSelectedReaction();

                setState(() {
                  _selectedReaction = null;
                  _selectedQuiz = null;
                });
              },
            ),

            const SizedBox(height: 10),

            if (staff.loadingReactionPrompt)
              const Padding(
                padding: EdgeInsets.symmetric(vertical: 12),
                child: Center(
                  child: CircularProgressIndicator(),
                ),
              )
            else if (staff.reactionPromptError != null)
              _ErrorCard(
                message: staff.reactionPromptError!,
                onRetry: _refresh,
              )
            else if (staff.selectedReactionPrompt != null)
                _ReactionPromptCard(
                  reaction: selectedReaction,
                  prompt: staff.selectedReactionPrompt!.prompt,
                ),

            const SizedBox(height: 10),

            PortalPrimaryButton(
              label: staff.importingQuizCsv
                  ? 'Đang import CSV...'
                  : 'Import CSV cho phản ứng này',
              icon: Icons.upload_file_outlined,
              loading: staff.importingQuizCsv,
              onPressed: staff.importingQuizCsv
                  ? null
                  : () => _pickAndImportCsv(
                selectedReaction.reactionCode,
              ),
            ),

            const SizedBox(height: 10),

            if (staff.loadingSelectedReactionQuizzes &&
                selectedQuizzes.isEmpty)
              const Padding(
                padding: EdgeInsets.only(top: 24),
                child: Center(
                  child: CircularProgressIndicator(),
                ),
              )
            else if (staff.selectedReactionQuizError != null)
              _ErrorCard(
                message: staff.selectedReactionQuizError!,
                onRetry: _refresh,
              )
            else if (selectedQuizzes.isEmpty)
                const _EmptyCard(
                  message:
                  'Phản ứng này chưa có quiz. Hãy import CSV để tạo quiz.',
                )
              else
                ...selectedQuizzes.map(
                      (quiz) => _QuizSummaryCard(
                    quiz: quiz,
                    onViewQuestions: () async {
                      setState(() {
                        _selectedQuiz = quiz;
                      });

                      await context
                          .read<StaffProvider>()
                          .loadQuizDetail(quiz.quizCode);
                    },
                  ),
                ),
          ] else ...[
            _SelectedQuizHeader(
              quiz: selectedQuiz,
              publishing: staff.publishingQuiz,
              onBack: () {
                context
                    .read<StaffProvider>()
                    .clearSelectedQuizDetail();

                setState(() {
                  _selectedQuiz = null;
                });
              },
              onPublish: () async {
                try {
                  await context
                      .read<StaffProvider>()
                      .publishQuiz(selectedQuiz.quizCode);

                  if (!context.mounted) return;

                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(
                      content: Text('Đã publish quiz'),
                    ),
                  );

                  await _refresh();
                } catch (e) {
                  if (!context.mounted) return;

                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(
                      content: Text('Publish thất bại: $e'),
                      backgroundColor: AppColors.error,
                    ),
                  );
                }
              },
            ),

            const SizedBox(height: 10),

            if (staff.loadingQuizDetail &&
                selectedQuizDetail == null)
              const Padding(
                padding: EdgeInsets.only(top: 24),
                child: Center(
                  child: CircularProgressIndicator(),
                ),
              )
            else if (staff.quizDetailError != null)
              _ErrorCard(
                message: staff.quizDetailError!,
                onRetry: _refresh,
              )
            else if (selectedQuizDetail == null)
                const _EmptyCard(
                  message: 'Không tìm thấy chi tiết quiz.',
                )
              else if (selectedQuizDetail.questions.items.isEmpty)
                  const _EmptyCard(
                    message: 'Quiz này chưa có câu hỏi.',
                  )
                else
                  ...selectedQuizDetail.questions.items.map(
                        (question) => _QuestionCard(
                      question: question,
                    ),
                  ),
          ],
        ],
      ),
    );
  }
}

class _ReactionQuizOverviewCard extends StatelessWidget {
  final StaffReactionQuizOverviewModel reaction;
  final VoidCallback onViewPrompt;
  final VoidCallback onViewQuizzes;

  const _ReactionQuizOverviewCard({
    required this.reaction,
    required this.onViewPrompt,
    required this.onViewQuizzes,
  });

  @override
  Widget build(BuildContext context) {
    final hasQuiz = reaction.hasQuiz;
    final status =
    reaction.latestQuizStatus?.toLowerCase();

    final statusColor = !hasQuiz
        ? AppColors.textSecondary
        : switch (status) {
      'published' => AppColors.success,
      'draft' => AppColors.amber,
      'ready' => AppColors.subtitleAccent,
      'archived' => AppColors.textSecondary,
      _ => AppColors.amber,
    };

    final statusLabel = !hasQuiz
        ? 'Chưa có quiz'
        : switch (status) {
      'published' => 'Đã publish',
      'draft' => 'Bản nháp',
      'ready' => 'Sẵn sàng',
      'archived' => 'Đã lưu trữ',
      _ => reaction.latestQuizStatus ?? 'Có quiz',
    };

    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: PortalGlassCard(
        accentBorder: statusColor,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                PortalBadge(
                  text: statusLabel,
                  color: statusColor,
                ),
                const Spacer(),
                Text(
                  reaction.reactionCode,
                  style: TextStyle(
                    fontSize: 10,
                    color: AppColors.textSecondary,
                    fontFamily: 'Inter',
                  ),
                ),
              ],
            ),
            const SizedBox(height: 10),
            Text(
              reaction.reactionName,
              style: TextStyle(
                fontSize: 15,
                fontWeight: FontWeight.w700,
                color: AppColors.textPrimary,
                fontFamily: 'Inter',
              ),
            ),
            const SizedBox(height: 4),
            Text(
              reaction.equation,
              style: TextStyle(
                fontSize: 12,
                color: AppColors.subtitleAccent,
                fontFamily: 'Inter',
              ),
            ),
            const SizedBox(height: 6),
            Text(
              'Lớp ${reaction.grade} • '
                  '${reaction.reactionCategory} • '
                  '${reaction.reactionType}',
              style: TextStyle(
                fontSize: 11,
                color: AppColors.textSecondary,
                fontFamily: 'Inter',
              ),
            ),
            if (hasQuiz) ...[
              const SizedBox(height: 10),
              Text(
                '${reaction.latestQuizTitle ?? 'Quiz'} '
                    '• ${reaction.questionCount} câu',
                style: TextStyle(
                  fontSize: 12,
                  color: AppColors.textSecondary,
                  fontFamily: 'Inter',
                ),
              ),
            ],
            const SizedBox(height: 12),
            Row(
              children: [
                Expanded(
                  child: OutlinedButton.icon(
                    onPressed: onViewPrompt,
                    icon: const Icon(
                      Icons.description_outlined,
                      size: 18,
                    ),
                    label: const Text('Prompt'),
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: ElevatedButton.icon(
                    onPressed: onViewQuizzes,
                    icon: const Icon(
                      Icons.quiz_outlined,
                      size: 18,
                    ),
                    label: const Text('Xem quiz'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.secondary,
                      foregroundColor: Colors.white,
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class _SelectedReactionHeader extends StatelessWidget {
  final StaffReactionQuizOverviewModel reaction;
  final VoidCallback onBack;

  const _SelectedReactionHeader({
    required this.reaction,
    required this.onBack,
  });

  @override
  Widget build(BuildContext context) {
    return PortalGlassCard(
      accentBorder: AppColors.subtitleAccent,
      child: Row(
        children: [
          IconButton(
            onPressed: onBack,
            icon: Icon(
              Icons.arrow_back,
              color: AppColors.subtitleAccent,
            ),
          ),
          const SizedBox(width: 6),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  reaction.reactionName,
                  style: TextStyle(
                    fontSize: 15,
                    fontWeight: FontWeight.w700,
                    color: AppColors.textPrimary,
                    fontFamily: 'Inter',
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  '${reaction.reactionCode} • '
                      '${reaction.equation}',
                  style: TextStyle(
                    fontSize: 11,
                    color: AppColors.textSecondary,
                    fontFamily: 'Inter',
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
class _ReactionPromptCard extends StatelessWidget {
  final StaffReactionQuizOverviewModel reaction;
  final String prompt;

  const _ReactionPromptCard({
    required this.reaction,
    required this.prompt,
  });

  @override
  Widget build(BuildContext context) {
    return PortalGlassCard(
      accentBorder: AppColors.secondary,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Prompt tạo CSV quiz',
            style: TextStyle(
              fontSize: 15,
              fontWeight: FontWeight.w700,
              color: AppColors.textPrimary,
              fontFamily: 'Inter',
            ),
          ),
          const SizedBox(height: 8),
          Text(
            reaction.reactionName,
            style: TextStyle(
              fontSize: 12,
              color: AppColors.subtitleAccent,
              fontFamily: 'Inter',
            ),
          ),
          const SizedBox(height: 4),
          Text(
            reaction.equation,
            style: TextStyle(
              fontSize: 11,
              color: AppColors.textSecondary,
              fontFamily: 'Inter',
            ),
          ),
          const SizedBox(height: 12),
          SizedBox(
            width: double.infinity,
            child: OutlinedButton.icon(
              onPressed: () async {
                await Clipboard.setData(
                  ClipboardData(text: prompt),
                );

                if (!context.mounted) return;

                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text('Đã copy prompt'),
                  ),
                );
              },
              icon: const Icon(Icons.copy, size: 18),
              label: const Text('Copy prompt'),
            ),
          ),
          const SizedBox(height: 12),
          Text(
            prompt,
            style: TextStyle(
              fontSize: 12,
              color: AppColors.textSecondary,
              fontFamily: 'Inter',
              height: 1.4,
            ),
          ),
        ],
      ),
    );
  }
}


class _SelectedQuizHeader extends StatelessWidget {
  final StaffQuizSummaryModel quiz;
  final VoidCallback onBack;
  final Future<void> Function() onPublish;
  final bool publishing;

  const _SelectedQuizHeader({
    required this.quiz,
    required this.onBack,
    required this.onPublish,
    required this.publishing,
  });

  @override
  Widget build(BuildContext context) {
    final isDraft = quiz.status.toLowerCase() == 'draft';
    final canPublish = isDraft && quiz.questionCount > 0;

    return PortalGlassCard(
      accentBorder: AppColors.subtitleAccent,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              IconButton(
                onPressed: onBack,
                icon: Icon(
                  Icons.arrow_back,
                  color: AppColors.subtitleAccent,
                ),
              ),
              const SizedBox(width: 6),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      quiz.title,
                      style: TextStyle(
                        fontSize: 15,
                        fontWeight: FontWeight.w700,
                        color: AppColors.textPrimary,
                        fontFamily: 'Inter',
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      '${quiz.questionCount} câu • ${quiz.status}',
                      style: TextStyle(
                        fontSize: 11,
                        color: AppColors.textSecondary,
                        fontFamily: 'Inter',
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          if (canPublish) ...[
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: publishing ? null : onPublish,
                icon: publishing
                    ? const SizedBox(
                  width: 16,
                  height: 16,
                  child: CircularProgressIndicator(strokeWidth: 2),
                )
                    : const Icon(Icons.public_outlined, size: 18),
                label: Text(publishing ? 'Đang publish...' : 'Publish quiz'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.success,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 12),
                ),
              ),
            ),
          ] else if (quiz.status.toLowerCase() == 'published') ...[
            const SizedBox(height: 12),
            PortalBadge(
              text: 'Quiz đã publish',
              color: AppColors.success,
            ),
          ],
        ],
      ),
    );
  }
}

class _QuizSummaryCard extends StatelessWidget {
  final StaffQuizSummaryModel quiz;
  final VoidCallback onViewQuestions;

  const _QuizSummaryCard({
    required this.quiz,
    required this.onViewQuestions,
  });

  @override
  Widget build(BuildContext context) {
    final status = quiz.status.toLowerCase();

    final Color statusColor = switch (status) {
      'published' => AppColors.success,
      'draft' => AppColors.amber,
      'reviewed' => AppColors.subtitleAccent,
      'archived' => AppColors.textSecondary,
      _ => AppColors.amber,
    };

    final String statusLabel = switch (status) {
      'published' => 'Đã publish',
      'draft' => 'Bản nháp',
      'reviewed' => 'Đã duyệt',
      'archived' => 'Đã lưu trữ',
      _ => quiz.status,
    };

    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: PortalGlassCard(
        accentBorder: statusColor,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                PortalBadge(text: statusLabel, color: statusColor),
                const Spacer(),
                Icon(
                  Icons.quiz_outlined,
                  size: 14,
                  color: AppColors.textSecondary,
                ),
                const SizedBox(width: 4),
                Text(
                  '${quiz.questionCount} câu',
                  style: TextStyle(
                    fontSize: 10,
                    color: AppColors.textSecondary,
                    fontFamily: 'Inter',
                  ),
                ),
              ],
            ),
            const SizedBox(height: 10),
            Text(
              quiz.title,
              style: TextStyle(
                fontSize: 15,
                fontWeight: FontWeight.w700,
                color: AppColors.textPrimary,
                fontFamily: 'Inter',
              ),
            ),
            const SizedBox(height: 4),
            Text(
              'Version ${quiz.version} • ${quiz.generatedBy}',
              style: TextStyle(
                fontSize: 12,
                color: AppColors.subtitleAccent,
                fontFamily: 'Inter',
              ),
            ),
            const SizedBox(height: 12),
            Align(
              alignment: Alignment.centerLeft,
              child: OutlinedButton.icon(
                onPressed: onViewQuestions,
                icon: Icon(
                  Icons.visibility_outlined,
                  size: 16,
                  color: AppColors.subtitleAccent,
                ),
                label: const Text(
                  'Xem câu hỏi',
                  overflow: TextOverflow.ellipsis,
                ),
                style: OutlinedButton.styleFrom(
                  foregroundColor: AppColors.subtitleAccent,
                  side: BorderSide(
                    color: AppColors.subtitleAccent.withValues(alpha: 0.45),
                  ),
                  padding: const EdgeInsets.symmetric(
                    horizontal: 14,
                    vertical: 10,
                  ),
                  minimumSize: const Size(0, 40),
                  tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _QuestionCard extends StatelessWidget {
  final StaffQuizQuestionModel question;

  const _QuestionCard({
    required this.question,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: PortalGlassCard(
        accentBorder: AppColors.subtitleAccent,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                PortalBadge(
                  text: 'Câu ${question.questionOrder}',
                  color: AppColors.subtitleAccent,
                ),
                const Spacer(),
                PortalBadge(
                  text: question.status,
                  color: AppColors.amber,
                ),
              ],
            ),
            const SizedBox(height: 10),
            Text(
              question.questionText,
              style: TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.w700,
                color: AppColors.textPrimary,
                fontFamily: 'Inter',
              ),
            ),
            if (question.options.isNotEmpty) ...[
              const SizedBox(height: 10),
              ...question.options.map((option) {
                final isCorrect =
                    option.optionKey.trim().toUpperCase() ==
                        question.correctAnswer
                            .trim()
                            .toUpperCase();

                return Padding(
                  padding: const EdgeInsets.only(bottom: 6),
                  child: Container(
                    width: double.infinity,
                    padding: const EdgeInsets.symmetric(
                      horizontal: 10,
                      vertical: 8,
                    ),
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(
                        color: isCorrect
                            ? AppColors.success.withValues(alpha: 0.7)
                            : AppColors.subtitleAccent.withValues(alpha: 0.25),
                      ),
                      color: isCorrect
                          ? AppColors.success.withValues(alpha: 0.10)
                          : Colors.transparent,
                    ),
                    child: Row(
                      crossAxisAlignment:
                      CrossAxisAlignment.start,
                      children: [
                        Text(
                          '${option.optionKey}. ',
                          style: TextStyle(
                            fontSize: 12,
                            fontWeight: FontWeight.w700,
                            color: isCorrect
                                ? AppColors.success
                                : AppColors.subtitleAccent,
                            fontFamily: 'Inter',
                          ),
                        ),
                        Expanded(
                          child: Text(
                            option.optionText,
                            style: TextStyle(
                              fontSize: 12,
                              color: AppColors.textSecondary,
                              fontFamily: 'Inter',
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                );
              }),
            ],
            const SizedBox(height: 8),
            Text(
              'Đáp án: ${question.correctAnswer}',
              style: TextStyle(
                fontSize: 12,
                color: AppColors.success,
                fontWeight: FontWeight.w600,
                fontFamily: 'Inter',
              ),
            ),
            if (question.explanation != null &&
                question.explanation!.isNotEmpty) ...[
              const SizedBox(height: 6),
              Text(
                question.explanation!,
                style: TextStyle(
                  fontSize: 12,
                  color: AppColors.textSecondary,
                  fontFamily: 'Inter',
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }
}

class _ErrorCard extends StatelessWidget {
  final String message;
  final Future<void> Function() onRetry;

  const _ErrorCard({
    required this.message,
    required this.onRetry,
  });

  @override
  Widget build(BuildContext context) {
    return PortalGlassCard(
      accentBorder: AppColors.error,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Không tải được dữ liệu quiz',
            style: TextStyle(
              fontSize: 15,
              fontWeight: FontWeight.w700,
              color: AppColors.textPrimary,
              fontFamily: 'Inter',
            ),
          ),
          const SizedBox(height: 8),
          Text(
            message,
            style: TextStyle(
              fontSize: 12,
              color: AppColors.textSecondary,
              fontFamily: 'Inter',
            ),
          ),
          const SizedBox(height: 12),
          OutlinedButton.icon(
            onPressed: onRetry,
            icon: const Icon(Icons.refresh),
            label: const Text('Thử lại'),
          ),
        ],
      ),
    );
  }
}

class _EmptyCard extends StatelessWidget {
  final String message;

  const _EmptyCard({required this.message});

  @override
  Widget build(BuildContext context) {
    return PortalGlassCard(
      child: Text(
        message,
        style: TextStyle(
          fontSize: 12,
          color: AppColors.textSecondary,
          fontFamily: 'Inter',
        ),
      ),
    );
  }
}