name: labedu
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+38
environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0            # Để gọi API đến Java BE
  provider: ^6.1.1       # Để quản lý trạng thái (State Management) cho các Folder presentation
  google_fonts: ^6.2.1   # Font Inter cho UI
  shared_preferences: ^2.2.2
  archive: ^4.0.0
  image_picker: ^1.2.2
  path_provider: ^2.1.5
  fl_chart: ^1.2.0
  file_picker: ^11.0.2
  amplify_flutter: ^2.7.0
  amplify_auth_cognito: ^2.7.0
  http: ^1.2.1
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.2
  app_links: ^6.3.2
  url_launcher: ^6.3.0
  path: ^1.9.0
  mime: ^2.0.0
  package_info_plus: ^9.0.0
  device_info_plus: ^12.4.0
  flutter_dotenv: ^6.0.1
  gal: ^2.3.1
  permission_handler: ^11.0.0
  in_app_purchase: ^3.3.0
  in_app_purchase_android: ^0.5.0
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  flutter_local_notifications: ^22.0.1
  flutter_markdown: ^0.7.7+1
  flutter_unity_widget_2:
    path: ./packages/flutter_unity_widget_2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/Cyber.png
    - assets/images/Light.png
    - assets/images/Ocean.png
    - assets/images/Galaxy.png
    - assets/images/Forest.png
    - assets/images/payment-qr.jpg
    - assets/images/ai_chat_fab_icon.png
    - assets/icon/app_icon.jpg
    - assets/images/ar_30_days.png


