unity.androidSdkPath=C:/Program Files/Unity/Hub/Editor/6000.4.7f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=C:/Program Files/Unity/Hub/Editor/6000.4.7f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=D\:\\Unity\\Editors\\6000.4.7f1\\Editor\\Data\\PlaybackEngines\\AndroidPlayer\\OpenJDK
