org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=.manifest
unityTemplateVersion=23
unityProjectPath=D:/Project 2026/Unity Project/Clone/My project-2026-05-19-13-56-49-2026-05-19-13-56-50
unity.projectPath=D:/Project 2026/Unity Project/Clone/My project-2026-05-19-13-56-49-2026-05-19-13-56-50
unity.debugSymbolLevel=none
unity.buildToolsVersion=36.0.0
unity.minSdkVersion=29
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.vuforia.engine.VuforiaEngine
unity.abiFilters=arm64-v8a
unity.versionCode=1144
unity.versionName=11.4.4
unity.namespace=com.vuforia.engine.VuforiaEngine
unity.agpVersion=9.0.0
unity.androidSdkPath=D\:\\Android\\Android_SDK
unity.androidNdkPath=D\:\\Android\\Android_SDK\\ndk\\28.2.13676358
unity.androidNdkVersion=28.2.13676358
unity.jdkPath=D\:\\Unity\\Editors\\6000.4.7f1\\Editor\\Data\\PlaybackEngines\\AndroidPlayer\\OpenJDK
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never