org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=false
unityStreamingAssets=
unity.androidSdkPath=D\:/Android/Android_SDK
unity.androidNdkPath=D\:/Android/Android_SDK/ndk/28.2.13676358
unity.androidNdkVersion=28.2.13676358
    

