// File generated by FlutterFire CLI — API keys loaded from .env / --dart-define.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'core/config/env_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// API keys are NOT hardcoded. Provide them via `.env` (see `.env.example`)
/// or `--dart-define=FIREBASE_*_API_KEY=...`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: EnvConfig.value(
          'FIREBASE_WEB_API_KEY',
          fromDefine: const String.fromEnvironment('FIREBASE_WEB_API_KEY'),
        ),
        appId: '1:71152616630:web:41da60f18db914e714d217',
        messagingSenderId: '71152616630',
        projectId: 'ar-chemistry-notification',
        authDomain: 'ar-chemistry-notification.firebaseapp.com',
        storageBucket: 'ar-chemistry-notification.firebasestorage.app',
        measurementId: 'G-6NMGHZ2D7D',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: EnvConfig.value(
          'FIREBASE_ANDROID_API_KEY',
          fromDefine: const String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
        ),
        appId: '1:71152616630:android:aa6b30f46d7fe1a514d217',
        messagingSenderId: '71152616630',
        projectId: 'ar-chemistry-notification',
        storageBucket: 'ar-chemistry-notification.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: EnvConfig.value(
          'FIREBASE_IOS_API_KEY',
          fromDefine: const String.fromEnvironment('FIREBASE_IOS_API_KEY'),
        ),
        appId: '1:71152616630:ios:bca717fcd25c2c0514d217',
        messagingSenderId: '71152616630',
        projectId: 'ar-chemistry-notification',
        storageBucket: 'ar-chemistry-notification.firebasestorage.app',
        iosBundleId: 'com.hoaianstudio.arChemistryVisual',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: EnvConfig.value(
          'FIREBASE_IOS_API_KEY',
          fromDefine: const String.fromEnvironment('FIREBASE_IOS_API_KEY'),
        ),
        appId: '1:71152616630:ios:bca717fcd25c2c0514d217',
        messagingSenderId: '71152616630',
        projectId: 'ar-chemistry-notification',
        storageBucket: 'ar-chemistry-notification.firebasestorage.app',
        iosBundleId: 'com.hoaianstudio.arChemistryVisual',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: EnvConfig.value(
          'FIREBASE_WEB_API_KEY',
          fromDefine: const String.fromEnvironment('FIREBASE_WEB_API_KEY'),
        ),
        appId: '1:71152616630:web:5e1584acd04a316414d217',
        messagingSenderId: '71152616630',
        projectId: 'ar-chemistry-notification',
        authDomain: 'ar-chemistry-notification.firebaseapp.com',
        storageBucket: 'ar-chemistry-notification.firebasestorage.app',
        measurementId: 'G-CPQ6E39Y4L',
      );
}
