// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvH-9xcYOzl5F0UQxJfgJ2HKKMse40dpY',
    appId: '1:71152616630:web:41da60f18db914e714d217',
    messagingSenderId: '71152616630',
    projectId: 'ar-chemistry-notification',
    authDomain: 'ar-chemistry-notification.firebaseapp.com',
    storageBucket: 'ar-chemistry-notification.firebasestorage.app',
    measurementId: 'G-6NMGHZ2D7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Zgk9CuI85BCbUdebbxylttLDZt5V_cM',
    appId: '1:71152616630:android:aa6b30f46d7fe1a514d217',
    messagingSenderId: '71152616630',
    projectId: 'ar-chemistry-notification',
    storageBucket: 'ar-chemistry-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChFLwekY_gemdJ7v7vB_BZ2NBA0tx6F1U',
    appId: '1:71152616630:ios:bca717fcd25c2c0514d217',
    messagingSenderId: '71152616630',
    projectId: 'ar-chemistry-notification',
    storageBucket: 'ar-chemistry-notification.firebasestorage.app',
    iosBundleId: 'com.hoaianstudio.arChemistryVisual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChFLwekY_gemdJ7v7vB_BZ2NBA0tx6F1U',
    appId: '1:71152616630:ios:bca717fcd25c2c0514d217',
    messagingSenderId: '71152616630',
    projectId: 'ar-chemistry-notification',
    storageBucket: 'ar-chemistry-notification.firebasestorage.app',
    iosBundleId: 'com.hoaianstudio.arChemistryVisual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvH-9xcYOzl5F0UQxJfgJ2HKKMse40dpY',
    appId: '1:71152616630:web:5e1584acd04a316414d217',
    messagingSenderId: '71152616630',
    projectId: 'ar-chemistry-notification',
    authDomain: 'ar-chemistry-notification.firebaseapp.com',
    storageBucket: 'ar-chemistry-notification.firebasestorage.app',
    measurementId: 'G-CPQ6E39Y4L',
  );
}
